# Generated by Django 3.1.3 on 2020-11-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('alg_id', models.TextField(blank=True, null=True)),
                ('alg', models.TextField(blank=True, null=True)),
                ('alg_has_gap', models.BooleanField(blank=True, null=True)),
                ('source_blocks', models.TextField(blank=True, null=True)),
                ('target_blocks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('level_0', models.BigIntegerField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('source_token', models.TextField(blank=True, null=True)),
                ('book', models.TextField(blank=True, null=True)),
                ('chapter', models.BigIntegerField(blank=True, null=True)),
                ('verse', models.BigIntegerField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('token_prefix', models.TextField(blank=True, null=True)),
                ('morph', models.TextField(blank=True, null=True)),
                ('lemma', models.TextField(blank=True, null=True)),
                ('strongs', models.TextField(blank=True, null=True)),
                ('strongs_no_prefix', models.TextField(blank=True, null=True)),
                ('has_prefix', models.BooleanField(blank=True, null=True)),
                ('translation_word', models.TextField(blank=True, null=True)),
                ('orig_id', models.BigIntegerField(blank=True, null=True)),
                ('occs', models.BigIntegerField(blank=True, null=True)),
                ('occ', models.BigIntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StrongsM2M',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('number', models.TextField(blank=True, null=True)),
                ('related_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'strongs_m2m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('orig_id', models.BigIntegerField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('chapter', models.BigIntegerField(blank=True, null=True)),
                ('verse', models.BigIntegerField(blank=True, null=True)),
                ('book', models.TextField(blank=True, null=True)),
                ('alg_id', models.TextField(blank=True, null=True)),
                ('target_token', models.TextField(blank=True, null=True)),
                ('target_token_prefix', models.TextField(blank=True, null=True)),
                ('target_blocks', models.TextField(blank=True, null=True)),
                ('target_occ', models.TextField(blank=True, null=True)),
                ('target_occs', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'target',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tw',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('refs', models.TextField(blank=True, null=True)),
                ('strongs', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tw',
                'managed': False,
            },
        ),
    ]
