# Generated by Django 3.1.3 on 2020-11-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alignment',
            options={'managed': True},
        ),
    ]
