# Generated by Django 3.1.3 on 2020-11-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_auto_20201118_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alignment',
            options={'managed': False},
        ),
    ]
