# Generated by Django 3.1.3 on 2021-05-21 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lexicon', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('examples', models.TextField()),
                ('extra_rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aim', models.TextField()),
                ('annotators', models.ManyToManyField(null=True, related_name='annotators', to=settings.AUTH_USER_MODEL)),
                ('editor_in_chief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editors', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.annotationlabel')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.annotationlabel')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.annotationscheme')),
                ('source_tokens', models.ManyToManyField(to='lexicon.Source')),
            ],
        ),
    ]
