# Generated by Django 3.1.3 on 2021-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20210521_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationscheme',
            name='labels',
        ),
        migrations.AddField(
            model_name='annotationscheme',
            name='labels',
            field=models.ManyToManyField(to='annotation.AnnotationLabel'),
        ),
    ]
