# Generated by Django 3.1.3 on 2021-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20210525_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationlabel',
            name='definition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='annotationlabel',
            name='examples',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='annotationlabel',
            name='extra_rules',
            field=models.TextField(null=True),
        ),
    ]
