# Generated by Django 3.1.3 on 2021-05-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20210525_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationscheme',
            name='labels',
        ),
        migrations.AddField(
            model_name='annotationlabel',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.annotationscheme'),
            preserve_default=False,
        ),
    ]
