# Generated by Django 3.1.3 on 2021-05-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_auto_20210526_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationlabel',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='annotation.annotationscheme'),
        ),
    ]
